git config --global user.name "Your Name"
git config --global user.email "example@gmail.com"
git config --global credential.helper "cache --timeout=7200"
git config --global color.ui "auto"
git config --global core.editor "nano -w"
git config --global merge.tool "meld"
